services:
  testassignment.api:
    build:
      context: .
      dockerfile: TestAssignment.API/Dockerfile
    ports:
      - 5555:8080
      - 5556:8081
    depends_on:
      - "db"
  
  db:
    image: postgres:latest
    container_name: db_test_assignment
    restart: unless-stopped
    environment:
      POSTGRES_DB: "TestAssignment"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "Qwerty123"
    ports:
      - 5436:5432
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: